'use client';

import Link from 'next/link';

export default function WatermarkingPage() {
  return (
    <main className="page">
      <header className="header">
        <div className="header-inner">
          <div className="logo">
            <Link href="/" className="logo-link">
              <span className="logo-text">Phalanx</span>
            </Link>
          </div>

          <nav className="nav-links">
            <Link href="/about" className="nav-link">
              About Us
            </Link>

            <Link href="/watermarking" className="nav-link active-link">
              Watermarking
            </Link>
          </nav>

          <div className="account-wrapper">
            <Link href="/account" className="account-button">
              Account
            </Link>
          </div>
        </div>
      </header>

      <section className="about-hero">
        <p className="eyebrow">Planned Feature</p>
        <h1 className="about-title">LLM Watermarking</h1>
        <p className="about-subtitle">
          Watermarking is a planned Phalanx feature designed to help identify
          and trace AI-generated content from language models.
        </p>
      </section>

      <section className="about-content">
        <div className="section-card">
          <h2>What Is LLM Watermarking?</h2>
          <p>
            LLM watermarking is a technique for adding a hidden statistical
            pattern to text generated by a language model. The goal is not to
            visibly change the text for normal users, but to make the output
            detectable later by a verification system.
          </p>

          <p>
            In simple terms, a watermark acts like a subtle signature. If a
            model produces text with a known watermarking method, that text may
            later be analyzed to estimate whether it likely came from that model
            or system.
          </p>
        </div>

        <div className="info-grid">
          <div className="info-card">
            <h2>Why It Matters</h2>
            <p>
              As LLM-generated content becomes more common, organizations may
              need ways to track where generated text came from, identify
              misuse, and distinguish human-written content from AI-assisted
              content.
            </p>
          </div>

          <div className="info-card">
            <h2>How It Helps</h2>
            <p>
              Watermarking can support accountability by giving developers,
              researchers, or organizations a way to verify whether text was
              likely produced by a specific AI system.
            </p>
          </div>
        </div>

        <div className="section-card">
          <h2>How the Concept Works</h2>
          <p>
            When a language model generates text, it repeatedly chooses the next
            token based on probability. A watermarking method can slightly guide
            those token choices so that the final output contains a pattern. The
            output still reads normally, but the pattern can be detected by
            software that knows what to look for.
          </p>

          <p>
            This does not usually mean placing an obvious label like “made by
            AI” inside the text. Instead, the watermark is hidden in the
            statistical structure of the generated words or tokens.
          </p>
        </div>


        <div className="section-card">
          <h2>Potential Benefits</h2>
          <p>
            Support detection of AI-generated text 
        </p>
          <p>
            Help trace generated content back to a model or system
            </p>
            <p>
            Improve accountability for deployed LLM applications
            </p>
            <p>
            Assist with audits, policy enforcement, and misuse analysis
            </p>
            <p>
            Complement jailbreak testing with content-origin verification
          </p>
          <ul className="clean-list">
            
          </ul>
        </div>

        <div className="section-card">
          <h2>Limitations and Challenges</h2>
          <p>
            Watermarking is not a perfect solution. Generated text can be
            edited, paraphrased, translated, shortened, or mixed with
            human-written text, which may weaken or remove the watermark.
            Different watermarking approaches also vary in accuracy, robustness,
            and ease of detection.
          </p>

          <p>
            Because of these limitations, watermarking should be treated as one
            tool in a larger AI safety and security workflow, not as a complete
            guarantee by itself.
          </p>
        </div>

        <div className="section-card">
          <h2>Current Status</h2>
          <p>
            Watermarking is not currently the primary implemented feature of
            Phalanx. It is a planned extension that the project may support in
            future development. The current platform direction focuses on
            jailbreak testing, adversarial evaluation, response analysis, and
            report generation.
          </p>
        </div>

        <div className="section-card repository-card">
          <h2>Phalanx Project</h2>
          <p>
            Watermarking fits into the larger Phalanx goal of making LLM safety
            evaluation more practical, repeatable, and understandable for users.
          </p>

          <div className="repo-links">
            <Link href="/about" className="repo-button secondary-button">
              Learn More About Phalanx
            </Link>

            <Link href="/demo" className="repo-button">
              Try the Demo
            </Link>
          </div>
        </div>
      </section>

      <footer className="footer">© 2025 Phalanx. All rights reserved.</footer>

      <style jsx global>{`
        body {
          margin: 0;
          font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI',
            sans-serif;
          color: #111827;
          background: #ffffff;
        }

        .page {
          min-height: 100vh;
          display: flex;
          flex-direction: column;
          background: #ffffff;
        }

        .header {
          border-bottom: 1px solid #e5e7eb;
          background: #ffffff;
        }

        .header-inner {
          max-width: 960px;
          margin: 0 auto;
          padding: 16px 24px;
          display: flex;
          align-items: center;
        }

        .logo {
          display: flex;
          align-items: center;
          gap: 8px;
          flex-shrink: 0;
        }

        .logo-link {
          text-decoration: none;
          color: inherit;
        }

        .logo-text {
          font-size: 18px;
          font-weight: 600;
          color: #111827;
        }

        .nav-links {
          display: flex;
          align-items: center;
          gap: 18px;
          margin-left: 32px;
          margin-right: auto;
        }

        .nav-link {
          font-size: 14px;
          color: #111827;
          text-decoration: none;
          font-weight: 500;
        }

        .nav-link:hover,
        .active-link {
          color: #4b5563;
          text-decoration: underline;
        }

        .account-wrapper {
          position: relative;
          flex-shrink: 0;
        }

        .account-button {
          border-radius: 9999px;
          border: 1px solid #d1d5db;
          padding: 6px 14px;
          font-size: 14px;
          background: #f9fafb;
          color: #111827;
          cursor: pointer;
          display: inline-flex;
          align-items: center;
          gap: 6px;
          text-decoration: none;
        }

        .account-button:hover {
          background: #f3f4f6;
        }

        .about-hero {
          max-width: 960px;
          margin: 0 auto;
          padding: 56px 24px 32px;
          text-align: center;
        }

        .eyebrow {
          margin: 0 0 10px;
          font-size: 13px;
          text-transform: uppercase;
          letter-spacing: 0.1em;
          color: #6b7280;
          font-weight: 600;
        }

        .about-title {
          font-size: 34px;
          line-height: 1.15;
          font-weight: 650;
          margin: 0 0 16px;
          color: #111827;
        }

        .about-subtitle {
          max-width: 700px;
          margin: 0 auto;
          font-size: 15px;
          line-height: 1.6;
          color: #4b5563;
        }

        .about-content {
          width: 100%;
          max-width: 960px;
          margin: 0 auto;
          padding: 15px 24px 56px;
          box-sizing: border-box;
        }

        .info-grid {
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));
        gap: 16px;
        margin-top: 16px;
        margin-bottom: 16px;
        }

        .info-card,
        .section-card {
          border-radius: 16px;
          border: 1px solid #000000;
          background: #ffffff;
          padding: 24px 22px;
        }

        .section-card {
          margin-top: 16px;
        }

        .info-card h2,
        .section-card h2 {
          margin: 0 0 12px;
          font-size: 18px;
          font-weight: 600;
          color: #111827;
        }

        .info-card p,
        .section-card p {
          margin: 0 0 12px;
          font-size: 14px;
          line-height: 1.65;
          color: #4b5563;
        }

        .info-card p:last-child,
        .section-card p:last-child {
          margin-bottom: 0;
        }

        .info-card ul,
        .clean-list {
          margin: 0;
          padding-left: 20px;
          color: #4b5563;
          font-size: 14px;
          line-height: 1.65;
        }

        .clean-list li {
          margin-bottom: 6px;
        }

        .repository-card {
          text-align: center;
        }

        .repo-links {
          display: flex;
          justify-content: center;
          gap: 12px;
          flex-wrap: wrap;
          margin-top: 16px;
        }

        .repo-button {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          border-radius: 9999px;
          border: 1px solid #111827;
          padding: 9px 16px;
          background: #111827;
          color: #ffffff;
          text-decoration: none;
          font-size: 14px;
          font-weight: 500;
        }

        .repo-button:hover {
          background: #374151;
        }

        .secondary-button {
          background: #ffffff;
          color: #111827;
        }

        .secondary-button:hover {
          background: #f3f4f6;
        }

        .footer {
          margin-top: auto;
          padding: 24px 16px 32px;
          font-size: 13px;
          text-align: center;
          color: #6b7280;
          border-top: 1px solid #f3f4f6;
        }

        @media (max-width: 768px) {
          .header-inner {
            flex-wrap: wrap;
            gap: 12px;
          }

          .nav-links {
            order: 3;
            width: 100%;
            margin-left: 0;
            margin-right: 0;
            justify-content: center;
          }

          .account-wrapper {
            margin-left: auto;
          }

          .about-title {
            font-size: 28px;
          }

          .info-grid {
            grid-template-columns: 1fr;
          }

          .repo-links {
            flex-direction: column;
          }

          .repo-button {
            width: 100%;
            box-sizing: border-box;
          }
        }
      `}</style>
    </main>
  );
}